In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [ ]:
measure_data = pd.read_csv('/content/measures-as-defined.csv')
Commodities_data = pd.read_csv('/content/commodities-report.csv')
MSC_data = pd.read_csv('/content/measures-on-declarable-commodities (1).csv')

In [ ]:
chunk_size = 100000

# Function to process each chunk (replace with your actual processing logic)
def process(chunk):
    return chunk

# List to store temporary file names
processed_chunks = []

# Step 1: Process data in chunks and save to temporary files
for i, chunk in enumerate(pd.read_csv('/content/measures-on-declarable-commodities (1).csv', chunksize=chunk_size)):
    processed_chunk = process(chunk)
    temp_filename = f'processed_chunk_{i}.csv'
    processed_chunk.to_csv(temp_filename, index=False)
    processed_chunks.append(temp_filename)

In [ ]:
# Step 2: Combine processed chunks
dataframes = []

for temp_filename in processed_chunks:
    df_chunk = pd.read_csv(temp_filename)
    dataframes.append(df_chunk)

MSC_data = pd.concat(dataframes, ignore_index=True)
MSC_data.to_csv('final_combined_dataset.csv', index=False)

In [ ]:
# Step 3: Load the combined dataset
MSC_data = pd.read_csv('final_combined_dataset.csv')

# Verify the loaded data
print(MSC_data.head())
print(MSC_data.info())

   id  commodity__sid  commodity__code  commodity__indent  \
0   1           93796        101210000                  2
1   2           93796        101210000                  2
2   3           93796        101210000                  2
3   4           93796        101210000                  2
4   5           93796        101210000                  2

       commodity__description  measure__sid  measure__type__id  \
0  Pure-bred breeding animals      20000000                103
1  Pure-bred breeding animals      20184077                103
2  Pure-bred breeding animals      20125835                142
3  Pure-bred breeding animals      20079764                142
4  Pure-bred breeding animals      20234871                142

  measure__type__description measure__additional_code__code  \
0         Third country duty                            NaN
1         Third country duty                            NaN
2          Tariff preference                            NaN
3          Tariff preference                            NaN
4          Tariff preference                            NaN

  measure__additional_code__description  ... measure__footnotes  \
0                                   NaN  ...                NaN
1                                   NaN  ...                NaN
2                                   NaN  ...                NaN
3                                   NaN  ...                NaN
4                                   NaN  ...                NaN

  measure__conditions measure__geographical_area__sid  \
0                 NaN                             400
1                 NaN                             505
2                 NaN                             349
3                 NaN                             351
4                 NaN                             455

   measure__geographical_area__id measure__geographical_area__description  \
0                            1011                              ERGA OMNES
1                            1080                         Channel Islands
2                            1013                          European Union
3                            1033                               CARIFORUM
4                            1034      Eastern and Southern Africa States

  measure__excluded_geographical_areas__ids  \
0                                       NaN
1                                       NaN
2                                       NaN
3                                       NaN
4                                     KM|MG

   measure__excluded_geographical_areas__descriptions  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                 Comoros|Madagascar

  measure__quota__order_number measure__regulation__id  \
0                          NaN          S.I. 2020/1430
1                          NaN          S.I. 2020/1430
2                          NaN                     NaN
3                          NaN                     NaN
4                          NaN                     NaN

                        measure__regulation__url
0  https://www.legislation.gov.uk/uksi/2020/1430
1  https://www.legislation.gov.uk/uksi/2020/1430
2                                            NaN
3                                            NaN
4                                            NaN

[5 rows x 24 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1098899 entries, 0 to 1098898
Data columns (total 24 columns):
 #   Column                                              Non-Null Count    Dtype
---  ------                                              --------------    -----
 0   id                                                  1098899 non-null  int64
 1   commodity__sid                                      1098899 non-null  int64
 2   commodity__code                                     1098899 non-null  int64
 3   commodity__indent                                   1098899 non-null  int64
 4   commodity__description                              1098899 non-null  object
 5   measure__sid                                        1098899 non-null  int64
 6   measure__type__id                                   1098899 non-null  int64
 7   measure__type__description                          1098899 non-null  object
 8   measure__additional_code__code                      15744 non-null    object
 9   measure__additional_code__description               15744 non-null    object
 10  measure__duty_expression                            952169 non-null   object
 11  measure__effective_start_date                       1098899 non-null  object
 12  measure__effective_end_date                         45791 non-null    object
 13  measure__reduction_indicator                        0 non-null        float64
 14  measure__footnotes                                  115210 non-null   object
 15  measure__conditions                                 172686 non-null   object
 16  measure__geographical_area__sid                     1098899 non-null  int64
 17  measure__geographical_area__id                      1098893 non-null  object
 18  measure__geographical_area__description             1098899 non-null  object
 19  measure__excluded_geographical_areas__ids           27572 non-null    object
 20  measure__excluded_geographical_areas__descriptions  27572 non-null    object
 21  measure__quota__order_number                        13889 non-null    float64
 22  measure__regulation__id                             414476 non-null   object
 23  measure__regulation__url                            403276 non-null   object
dtypes: float64(2), int64(7), object(15)
memory usage: 201.2+ MB
None

In [ ]:
MSC_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1098899 entries, 0 to 1098898
Data columns (total 24 columns):
 #   Column                                              Non-Null Count    Dtype
---  ------                                              --------------    -----
 0   id                                                  1098899 non-null  int64
 1   commodity__sid                                      1098899 non-null  int64
 2   commodity__code                                     1098899 non-null  int64
 3   commodity__indent                                   1098899 non-null  int64
 4   commodity__description                              1098899 non-null  object
 5   measure__sid                                        1098899 non-null  int64
 6   measure__type__id                                   1098899 non-null  int64
 7   measure__type__description                          1098899 non-null  object
 8   measure__additional_code__code                      15744 non-null    object
 9   measure__additional_code__description               15744 non-null    object
 10  measure__duty_expression                            952169 non-null   object
 11  measure__effective_start_date                       1098899 non-null  object
 12  measure__effective_end_date                         45791 non-null    object
 13  measure__reduction_indicator                        0 non-null        float64
 14  measure__footnotes                                  115210 non-null   object
 15  measure__conditions                                 172686 non-null   object
 16  measure__geographical_area__sid                     1098899 non-null  int64
 17  measure__geographical_area__id                      1098893 non-null  object
 18  measure__geographical_area__description             1098899 non-null  object
 19  measure__excluded_geographical_areas__ids           27572 non-null    object
 20  measure__excluded_geographical_areas__descriptions  27572 non-null    object
 21  measure__quota__order_number                        13889 non-null    float64
 22  measure__regulation__id                             414476 non-null   object
 23  measure__regulation__url                            403276 non-null   object
dtypes: float64(2), int64(7), object(15)
memory usage: 201.2+ MB

In [ ]:
measure_data

,id,commodity__sid,commodity__code,commodity__indent,commodity__description,measure__sid,measure__type__id,measure__type__description,measure__additional_code__code,measure__additional_code__description,...,measure__footnotes,measure__conditions,measure__geographical_area__sid,measure__geographical_area__id,measure__geographical_area__description,measure__excluded_geographical_areas__ids,measure__excluded_geographical_areas__descriptions,measure__quota__order_number,measure__regulation__id,measure__regulation__url
0,1,27623,100000000,0,LIVE ANIMALS,20184077,103,Third country duty,NaN,NaN,...,NaN,NaN,505,1080,Channel Islands,NaN,NaN,NaN,S.I. 2020/1430,https://www.legislation.gov.uk/uksi/2020/1430
1,2,27623,100000000,0,LIVE ANIMALS,20125835,142,Tariff preference,NaN,NaN,...,NaN,NaN,349,1013,European Union,NaN,NaN,NaN,NaN,NaN
2,3,27623,100000000,0,LIVE ANIMALS,20079764,142,Tariff preference,NaN,NaN,...,NaN,NaN,351,1033,CARIFORUM,NaN,NaN,NaN,NaN,NaN
3,4,27623,100000000,0,LIVE ANIMALS,20234871,142,Tariff preference,NaN,NaN,...,NaN,NaN,455,1034,Eastern and Southern Africa States,KM|MG,Comoros|Madagascar,NaN,NaN,NaN
4,5,27623,100000000,0,LIVE ANIMALS,20079954,142,Tariff preference,NaN,NaN,...,NaN,NaN,468,1035,SADC EPA,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84923,84924,84894,9880840000,1,Classified in Chapter 84,20233381,724,Import control of fluorinated greenhouse gases,NaN,NaN,...,NaN,"condition:B,certificate:Y054,action:26|conditi...",400,1011,ERGA OMNES,NaN,NaN,NaN,517/2014,https://www.legislation.gov.uk/eur/2014/517
84924,84925,84895,9880850000,1,Classified in Chapter 85,20233382,724,Import control of fluorinated greenhouse gases,NaN,NaN,...,NaN,"condition:B,certificate:Y054,action:26|conditi...",400,1011,ERGA OMNES,NaN,NaN,NaN,517/2014,https://www.legislation.gov.uk/eur/2014/517
84925,84926,93473,9905000000,1,Personal property belonging to natural persons...,20192037,103,Third country duty,NaN,NaN,...,NaN,NaN,400,1011,ERGA OMNES,NaN,NaN,NaN,2020/1430,NaN
84926,84927,93473,9905000000,1,Personal property belonging to natural persons...,20228418,103,Third country duty,NaN,NaN,...,NaN,NaN,505,1080,Channel Islands,NaN,NaN,NaN,2020/1430,NaN
84927,84928,93474,9919000000,1,"The following goods, other than those mentione...",20192038,103,Third country duty,NaN,NaN,...,NaN,NaN,400,1011,ERGA OMNES,NaN,NaN,NaN,2020/1430,NaN

In [ ]:
measure_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84928 entries, 0 to 84927
Data columns (total 24 columns):
 #   Column                                              Non-Null Count  Dtype
---  ------                                              --------------  -----
 0   id                                                  84928 non-null  int64
 1   commodity__sid                                      84928 non-null  int64
 2   commodity__code                                     84928 non-null  int64
 3   commodity__indent                                   84928 non-null  int64
 4   commodity__description                              84928 non-null  object
 5   measure__sid                                        84928 non-null  int64
 6   measure__type__id                                   84928 non-null  int64
 7   measure__type__description                          84928 non-null  object
 8   measure__additional_code__code                      10356 non-null  object
 9   measure__additional_code__description               10356 non-null  object
 10  measure__duty_expression                            55841 non-null  object
 11  measure__effective_start_date                       84928 non-null  object
 12  measure__effective_end_date                         12173 non-null  object
 13  measure__reduction_indicator                        0 non-null      float64
 14  measure__footnotes                                  23942 non-null  object
 15  measure__conditions                                 30848 non-null  object
 16  measure__geographical_area__sid                     84928 non-null  int64
 17  measure__geographical_area__id                      84922 non-null  object
 18  measure__geographical_area__description             84928 non-null  object
 19  measure__excluded_geographical_areas__ids           2222 non-null   object
 20  measure__excluded_geographical_areas__descriptions  2222 non-null   object
 21  measure__quota__order_number                        5033 non-null   float64
 22  measure__regulation__id                             50562 non-null  object
 23  measure__regulation__url                            49980 non-null  object
dtypes: float64(2), int64(7), object(15)
memory usage: 15.6+ MB

In [ ]:
measure_data .isnull().sum()

id                                                        0
commodity__sid                                            0
commodity__code                                           0
commodity__indent                                         0
commodity__description                                    0
measure__sid                                              0
measure__type__id                                         0
measure__type__description                                0
measure__additional_code__code                        74572
measure__additional_code__description                 74572
measure__duty_expression                              29087
measure__effective_start_date                             0
measure__effective_end_date                           72755
measure__reduction_indicator                          84928
measure__footnotes                                    60986
measure__conditions                                   54080
measure__geographical_area__sid                           0
measure__geographical_area__id                            6
measure__geographical_area__description                   0
measure__excluded_geographical_areas__ids             82706
measure__excluded_geographical_areas__descriptions    82706
measure__quota__order_number                          79895
measure__regulation__id                               34366
measure__regulation__url                              34948
dtype: int64

In [ ]:
measure_data.duplicated().sum()

0

In [ ]:
Commodities_data

,id,commodity__sid,commodity__code,commodity__suffix,commodity__description,commodity__validity_start,commodity__validity_end,parent__sid,parent__code,parent__suffix
0,1,27623,100000000,80,LIVE ANIMALS,1971-12-31,NaN,NaN,NaN,NaN
1,2,27624,101000000,80,"Live horses, asses, mules and hinnies",1972-01-01,NaN,27623.0,1.000000e+08,80.0
2,3,93797,101210000,10,Horses,2012-01-01,NaN,27624.0,1.010000e+08,80.0
3,4,93796,101210000,80,Pure-bred breeding animals,2012-01-01,NaN,93797.0,1.012100e+08,10.0
4,5,93798,101290000,80,Other,2012-01-01,NaN,93797.0,1.012100e+08,10.0
...,...,...,...,...,...,...,...,...,...,...
25818,25819,90779,9931000000,80,Goods delivered for the crew of the offshore i...,2009-01-01,NaN,88694.0,9.900000e+09,80.0
25819,25820,90780,9931240000,80,Goods of CN Chapters 1 to 24,2009-01-01,NaN,90779.0,9.931000e+09,80.0
25820,25821,90781,9931270000,80,Goods of CN Chapter 27,2009-01-01,NaN,90779.0,9.931000e+09,80.0
25821,25822,90782,9931990000,80,Goods classified elsewhere,2009-01-01,NaN,90779.0,9.931000e+09,80.0
25822,25823,93476,9950000000,80,"Code used only in intra-Union trade, for all t...",2011-01-01,NaN,88694.0,9.900000e+09,80.0

In [ ]:
Commodities_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25823 entries, 0 to 25822
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         25823 non-null  int64
 1   commodity__sid             25823 non-null  int64
 2   commodity__code            25823 non-null  int64
 3   commodity__suffix          25823 non-null  int64
 4   commodity__description     25823 non-null  object
 5   commodity__validity_start  25823 non-null  object
 6   commodity__validity_end    1 non-null      object
 7   parent__sid                25725 non-null  float64
 8   parent__code               25725 non-null  float64
 9   parent__suffix             25725 non-null  float64
dtypes: float64(3), int64(4), object(3)
memory usage: 2.0+ MB

In [ ]:
Commodities_data.isnull().sum()

id                               0
commodity__sid                   0
commodity__code                  0
commodity__suffix                0
commodity__description           0
commodity__validity_start        0
commodity__validity_end      25822
parent__sid                     98
parent__code                    98
parent__suffix                  98
dtype: int64

In [ ]:
Commodities_data.duplicated().sum()

0

In [ ]:
cols = ['commodity__code','measure__sid','measure__type__description','commodity__indent']

In [ ]:
df1 = measure_data[cols]

In [ ]:
df1

,commodity__code,measure__sid,measure__type__description,commodity__indent
0,100000000,20184077,Third country duty,0
1,100000000,20125835,Tariff preference,0
2,100000000,20079764,Tariff preference,0
3,100000000,20234871,Tariff preference,0
4,100000000,20079954,Tariff preference,0
...,...,...,...,...
84923,9880840000,20233381,Import control of fluorinated greenhouse gases,1
84924,9880850000,20233382,Import control of fluorinated greenhouse gases,1
84925,9905000000,20192037,Third country duty,1
84926,9905000000,20228418,Third country duty,1
84927,9919000000,20192038,Third country duty,1

In [ ]:
df1.isnull().sum()

commodity__code               0
measure__sid                  0
measure__type__description    0
commodity__indent             0
dtype: int64

In [ ]:
cols2 = ['commodity__code','commodity__suffix','commodity__validity_start','commodity__sid','commodity__description']

In [ ]:

df2 = Commodities_data[cols2]

In [ ]:
df2

,commodity__code,commodity__suffix,commodity__validity_start,commodity__sid,commodity__description
0,100000000,80,1971-12-31,27623,LIVE ANIMALS
1,101000000,80,1972-01-01,27624,"Live horses, asses, mules and hinnies"
2,101210000,10,2012-01-01,93797,Horses
3,101210000,80,2012-01-01,93796,Pure-bred breeding animals
4,101290000,80,2012-01-01,93798,Other
...,...,...,...,...,...
25818,9931000000,80,2009-01-01,90779,Goods delivered for the crew of the offshore i...
25819,9931240000,80,2009-01-01,90780,Goods of CN Chapters 1 to 24
25820,9931270000,80,2009-01-01,90781,Goods of CN Chapter 27
25821,9931990000,80,2009-01-01,90782,Goods classified elsewhere
25822,9950000000,80,2011-01-01,93476,"Code used only in intra-Union trade, for all t..."

In [ ]:
merged_df = pd.merge(df1, df2, on='commodity__code', how='inner')

In [ ]:
merged_df

,commodity__code,measure__sid,measure__type__description,commodity__indent,commodity__suffix,commodity__validity_start,commodity__sid,commodity__description
0,100000000,20184077,Third country duty,0,80,1971-12-31,27623,LIVE ANIMALS
1,100000000,20125835,Tariff preference,0,80,1971-12-31,27623,LIVE ANIMALS
2,100000000,20079764,Tariff preference,0,80,1971-12-31,27623,LIVE ANIMALS
3,100000000,20234871,Tariff preference,0,80,1971-12-31,27623,LIVE ANIMALS
4,100000000,20079954,Tariff preference,0,80,1971-12-31,27623,LIVE ANIMALS
...,...,...,...,...,...,...,...,...
101403,9905000000,20192037,Third country duty,1,10,2011-01-01,93477,"Certain goods, as provided for in Council Regu..."
101404,9905000000,20192037,Third country duty,1,80,2011-01-01,93473,Personal property belonging to natural persons...
101405,9905000000,20228418,Third country duty,1,10,2011-01-01,93477,"Certain goods, as provided for in Council Regu..."
101406,9905000000,20228418,Third country duty,1,80,2011-01-01,93473,Personal property belonging to natural persons...
101407,9919000000,20192038,Third country duty,1,80,2011-01-01,93474,"The following goods, other than those mentione..."

In [ ]:
merged_df.isnull().sum()

commodity__code               0
measure__sid                  0
measure__type__description    0
commodity__indent             0
commodity__suffix             0
commodity__validity_start     0
commodity__sid                0
commodity__description        0
dtype: int64

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101408 entries, 0 to 101407
Data columns (total 8 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   commodity__code             101408 non-null  int64
 1   measure__sid                101408 non-null  int64
 2   measure__type__description  101408 non-null  object
 3   commodity__indent           101408 non-null  int64
 4   commodity__suffix           101408 non-null  int64
 5   commodity__validity_start   101408 non-null  object
 6   commodity__sid              101408 non-null  int64
 7   commodity__description      101408 non-null  object
dtypes: int64(5), object(3)
memory usage: 6.2+ MB

In [ ]:
cols3 = ['commodity__code','measure__geographical_area__sid','measure__geographical_area__description','measure__duty_expression']

In [ ]:
df3 = MSC_data[cols3]

In [ ]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1098899 entries, 0 to 1098898
Data columns (total 4 columns):
 #   Column                                   Non-Null Count    Dtype
---  ------                                   --------------    -----
 0   commodity__code                          1098899 non-null  int64
 1   measure__geographical_area__sid          1098899 non-null  int64
 2   measure__geographical_area__description  1098899 non-null  object
 3   measure__duty_expression                 952169 non-null   object
dtypes: int64(2), object(2)
memory usage: 33.5+ MB

In [ ]:
merged_df1 = pd.merge(merged_df, df3,  on='commodity__code', how='inner')

In [ ]:
merged_df1.dropna(inplace=True)

In [ ]:
merged_df1.drop_duplicates(inplace=True)

In [ ]:
merged_df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3730153 entries, 0 to 5993406
Data columns (total 11 columns):
 #   Column                                   Dtype
---  ------                                   -----
 0   commodity__code                          int64
 1   measure__sid                             int64
 2   measure__type__description               object
 3   commodity__indent                        int64
 4   commodity__suffix                        int64
 5   commodity__validity_start                object
 6   commodity__sid                           int64
 7   commodity__description                   object
 8   measure__geographical_area__sid          int64
 9   measure__geographical_area__description  object
 10  measure__duty_expression                 object
dtypes: int64(6), object(5)
memory usage: 341.5+ MB

In [ ]:
merged_df1['commodity__code'] = merged_df1['commodity__code'].astype('int32')
merged_df1['commodity__sid'] = merged_df1['commodity__sid'].astype('int32')
merged_df1['measure__sid'] = merged_df1['measure__sid'].astype('int32')
merged_df1['commodity__indent'] = merged_df1['commodity__indent'].astype('int32')
merged_df1['commodity__suffix'] = merged_df1['commodity__suffix'].astype('int32')
merged_df1['measure__geographical_area__sid'] = merged_df1['measure__geographical_area__sid'].astype('int32')

In [ ]:
merged_df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3730153 entries, 0 to 5993406
Data columns (total 11 columns):
 #   Column                                   Dtype
---  ------                                   -----
 0   commodity__code                          int32
 1   measure__sid                             int32
 2   measure__type__description               object
 3   commodity__indent                        int32
 4   commodity__suffix                        int32
 5   commodity__validity_start                object
 6   commodity__sid                           int32
 7   commodity__description                   object
 8   measure__geographical_area__sid          int32
 9   measure__geographical_area__description  object
 10  measure__duty_expression                 object
dtypes: int32(6), object(5)
memory usage: 256.1+ MB

In [ ]:

# Save the merged dataset
#merged_df1.to_csv('dataset.csv', index=False)

In [ ]:
MSC_data_cleaned = merged_df1.iloc[1:1500000]

In [ ]:
# Use the isin() method to check for multiple values
african_countries = ["Algeria", "Angola", "Benin", "Botswana", "Burkina Faso", "Burundi", "Cabo Verde", "Cameroon",
               "Central African Republic", "Chad", "Comoros", "Congo", "Djibouti", "Egypt", "Equatorial Guinea",
               "Eritrea", "Eswatini", "Ethiopia", "Gabon", "Gambia", "Ghana", "Guinea", "Guinea-Bissau",
               "Ivory Coast", "Kenya", "Lesotho", "Liberia", "Libya", "Madagascar", "Malawi", "Mali", "Mauritania",
               "Mauritius", "Morocco", "Mozambique", "Namibia", "Niger", "Nigeria", "Rwanda", "Sao Tome and Principe",
               "Senegal", "Seychelles", "Sierra Leone", "Somalia", "South Africa", "South Sudan", "Sudan", "Tanzania",
               "Togo", "Tunisia", "Uganda", "Zambia", "Zimbabwe"]
MSC_data_africa = MSC_data_cleaned[MSC_data_cleaned['measure__geographical_area__description'].isin(african_countries)]

In [ ]:
Asia = ["Afghanistan", "Armenia", "Azerbaijan", "Bahrain", "Bangladesh", "Bhutan", "Brunei", "Cambodia", "China",
             "Cyprus", "Georgia", "India", "Indonesia", "Iran", "Iraq", "Israel", "Japan", "Jordan", "Kazakhstan",
             "Kuwait", "Kyrgyzstan", "Laos", "Lebanon", "Malaysia", "Maldives", "Mongolia", "Myanmar", "Nepal",
             "North Korea", "Oman", "Pakistan", "Palestine", "Philippines", "Qatar", "Saudi Arabia", "Singapore",
             "South Korea", "Sri Lanka", "Syria", "Tajikistan", "Thailand", "Timor-Leste", "Turkey", "Turkmenistan",
             "United Arab Emirates", "Uzbekistan", "Vietnam", "Yemen"] # Define the Asia variable as a list of countries
MSC_data_Asia = MSC_data_cleaned[MSC_data_cleaned['measure__geographical_area__description'].isin(Asia)]

In [ ]:
MSC_data_Asia.to_csv('Msc_data_asia.csv', index = False)

In [ ]:
Europe = ["Albania", "Andorra", "Armenia", "Austria", "Azerbaijan", "Belarus", "Belgium", "Bosnia and Herzegovina",
               "Bulgaria", "Croatia", "Cyprus", "Czech Republic", "Denmark", "Estonia", "Finland", "France", "Georgia",
               "Germany", "Greece", "Hungary", "Iceland", "Ireland", "Italy", "Kosovo", "Latvia", "Liechtenstein",
               "Lithuania", "Luxembourg", "Malta", "Moldova", "Monaco", "Montenegro", "Netherlands", "North Macedonia",
               "Norway", "Poland", "Portugal", "Romania", "Russia", "San Marino", "Serbia", "Slovakia", "Slovenia",
               "Spain", "Sweden", "Switzerland", "Ukraine", "United Kingdom", "Vatican City"]
MSC_data_Europe = MSC_data_cleaned[MSC_data_cleaned['measure__geographical_area__description'].isin(Europe)]

In [ ]:
MSC_data_Europe.to_csv('Msc_data_Europe.csv', index = False)

In [ ]:
MSC_data_Europe.info()

<class 'pandas.core.frame.DataFrame'>
Index: 329760 entries, 9 to 1709780
Data columns (total 11 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   commodity__code                          329760 non-null  int32
 1   measure__sid                             329760 non-null  int32
 2   measure__type__description               329760 non-null  object
 3   commodity__indent                        329760 non-null  int32
 4   commodity__suffix                        329760 non-null  int32
 5   commodity__validity_start                329760 non-null  object
 6   commodity__sid                           329760 non-null  int32
 7   commodity__description                   329760 non-null  object
 8   measure__geographical_area__sid          329760 non-null  int32
 9   measure__geographical_area__description  329760 non-null  object
 10  measure__duty_expression                 329760 non-null  object
dtypes: int32(6), object(5)
memory usage: 22.6+ MB

In [ ]:
North_America = ["Antigua and Barbuda", "Bahamas", "Barbados", "Belize", "Canada", "Costa Rica", "Cuba", "Dominica",
                      "Dominican Republic", "El Salvador", "Grenada", "Guatemala", "Haiti", "Honduras", "Jamaica",
                      "Mexico", "Nicaragua", "Panama", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines",
                      "Trinidad and Tobago", "United States"]
MSC_data_North_America = MSC_data_cleaned[MSC_data_cleaned['measure__geographical_area__description'].isin(North_America)]

In [ ]:
MSC_data_North_America.to_csv('Msc_data_North_America.csv', index = False)

In [ ]:
MSC_data_North_America.info()

<class 'pandas.core.frame.DataFrame'>
Index: 53992 entries, 11 to 1709757
Data columns (total 11 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   commodity__code                          53992 non-null  int32
 1   measure__sid                             53992 non-null  int32
 2   measure__type__description               53992 non-null  object
 3   commodity__indent                        53992 non-null  int32
 4   commodity__suffix                        53992 non-null  int32
 5   commodity__validity_start                53992 non-null  object
 6   commodity__sid                           53992 non-null  int32
 7   commodity__description                   53992 non-null  object
 8   measure__geographical_area__sid          53992 non-null  int32
 9   measure__geographical_area__description  53992 non-null  object
 10  measure__duty_expression                 53992 non-null  object
dtypes: int32(6), object(5)
memory usage: 3.7+ MB

In [ ]:
Oceania = ["Australia", "Fiji", "Kiribati", "Marshall Islands", "Micronesia", "Nauru", "New Zealand", "Palau",
          "Papua New Guinea", "Samoa", "Solomon Islands", "Tonga", "Tuvalu", "Vanuatu"]

MSC_data_Oceania = MSC_data_cleaned[MSC_data_cleaned['measure__geographical_area__description'].isin(Oceania)]

In [ ]:
MSC_data_Oceania.to_csv('Msc_data_Oceania.csv', index = False)

In [ ]:
MSC_data_Oceania.info()

<class 'pandas.core.frame.DataFrame'>
Index: 172838 entries, 10 to 1709770
Data columns (total 11 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   commodity__code                          172838 non-null  int32
 1   measure__sid                             172838 non-null  int32
 2   measure__type__description               172838 non-null  object
 3   commodity__indent                        172838 non-null  int32
 4   commodity__suffix                        172838 non-null  int32
 5   commodity__validity_start                172838 non-null  object
 6   commodity__sid                           172838 non-null  int32
 7   commodity__description                   172838 non-null  object
 8   measure__geographical_area__sid          172838 non-null  int32
 9   measure__geographical_area__description  172838 non-null  object
 10  measure__duty_expression                 172838 non-null  object
dtypes: int32(6), object(5)
memory usage: 11.9+ MB

In [ ]:
South_America = ["Argentina", "Bolivia", "Brazil", "Chile", "Colombia", "Ecuador", "Guyana", "Paraguay", "Peru",
                      "Suriname", "Uruguay", "Venezuela"]
MSC_data_South_America = MSC_data_cleaned[MSC_data_cleaned['measure__geographical_area__description'].isin(South_America)]
MSC_data_South_America.info()

<class 'pandas.core.frame.DataFrame'>
Index: 110154 entries, 14 to 1709760
Data columns (total 11 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   commodity__code                          110154 non-null  int32
 1   measure__sid                             110154 non-null  int32
 2   measure__type__description               110154 non-null  object
 3   commodity__indent                        110154 non-null  int32
 4   commodity__suffix                        110154 non-null  int32
 5   commodity__validity_start                110154 non-null  object
 6   commodity__sid                           110154 non-null  int32
 7   commodity__description                   110154 non-null  object
 8   measure__geographical_area__sid          110154 non-null  int32
 9   measure__geographical_area__description  110154 non-null  object
 10  measure__duty_expression                 110154 non-null  object
dtypes: int32(6), object(5)
memory usage: 7.6+ MB

In [ ]:
MSC_data_South_America.to_csv('MSC_data_South_America.csv', index = False)

In [ ]:
unique_geographical_areas = ['ERGA OMNES', 'Channel Islands', 'European Union', 'CARIFORUM',
       'Eastern and Southern Africa States', 'SADC EPA',
       'Developing Countries Trading Scheme (DCTS) - Comprehensive Preferences',
       'OCTs (Overseas Countries and Territories)',
       'Occupied Palestinian Territories', 'Solomon Islands',
       'Developing Countries Trading Scheme (DCTS) - Standard Preferences',
       'Developing Countries Trading Scheme (DCTS) - Enhanced Preferences',
       'Countries other than Member States of the European Union',
       'EU-Canada agreement: re-imported goods',
       'GSP – General Framework', 'Member countries of WTO',
       'Countries not members of the WTO',
       'Countries and territories subject to UK safeguards for goods category  A[1]']

In [ ]:
# Check unique geographical areas to ensure all countries/areas are mapped correctly
unique_geographical_areas = MSC_data_cleaned['measure__geographical_area__description'].unique()

In [ ]:
MSC_data_unique_geographical_areas.to_csv('MSC_data_unique_geographical_areas.csv', index = False)

In [ ]:
MSC_data_unique_geographical_areas = MSC_data_cleaned[MSC_data_cleaned['measure__geographical_area__description'].isin(unique_geographical_areas)]